[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

# Colors (GitHub Dark)

# Default colors
[colors.primary]
background = '0x101216'
foreground = '0x8b949e'

[colors.cursor]
text   = '0x101216'
cursor = '0xc9d1d9'


# Normal colors
[colors.normal]
black   = '0x000000'
red     = '0xf78166'
green   = '0x56d364'
yellow  = '0xe3b341'
blue    = '0x6ca4f8'
magenta = '0xdb61a2'
cyan    = '0x2b7489'
white   = '0xffffff'

# Bright colors
[colors.bright]
black   = '0x4c4c4c'
red     = '0xf78166'
green   = '0x56d364'
yellow  = '0xe3b341'
blue    = '0x6ca4f8'
magenta = '0xdb61a2'
cyan    = '0x2b7489'
white   = '0xffffff'
